env: dev
spring:
  application:
    name: client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root123
    password: root123
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false

