env: dev
spring:
  application:
    name: client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz@WSX3edc$RFV
    url: jdbc:mysql://11.1.3.53:13306/ruixun?characterEncoding=utf-8&useSSL=false

